<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 120px">

# Project 3 (Replace with real title later)
### (Fill out this cell as the project progresses, then move to README.md as technical report.)

*Deval Mehta*

## Table of Contents
1) [Overview](#Overview) 
2) [Data](#Data-Dictionary)
3) [Requirements](#Requirements)
4) [Executive Summary](#Executive-Summary)
    1) [The Data](#<The Deta>)
    2) [Baseline Values](#<Baseline Values>)
    3) [Data Transformation](#<Data Transformation>)
    4) [Model Selection Criteria](#<Model Selection Criteria>)
    5) [Analysis](#Analysis)
    6) [Implications](#Implications)
    8) [Next Steps](#Next-Steps)

## Overview

## Data Dictionary

| Variable | Data Type | Description | Notes |
|---|---|---|---|

## Requirements

| Library | Module | Purpose |
|---|---|---|

## Executive Summary
### The Data

### Baseline Values

### Data Transformation

### Model Selection Criteria

### Analysis

### Implications

### Next Steps

In [24]:
# Imports
import nltk
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import praw

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from reddit_scraper import *

### Load the Data in

In [25]:
# Retrieve top 1000 posts of all time from r/DungeonsAndDragons and r/Pathfinder_RPG
unified_data('DungeonsAndDragons', 'all', 1000, 1000)
unified_data('Pathfinder_RPG', 'all', 1000, 1000)

### Inspect the Data

In [26]:
dnd = pd.read_csv('../data/DungeonsAndDragons.csv')
pathfinder = pd.read_csv('../data/Pathfinder_RPG.csv')

display(dnd.head())
display(pathfinder.head())

,Unnamed: 0,id,created_utc,title,self_text,subreddit
0,0,7yx5bd,1.519144e+09,When you confuse Wisdom with Intelligence,NaN,DungeonsAndDragons
1,1,kutjp1,1.610334e+09,"Live out your fantasy this way, and you will b...",NaN,DungeonsAndDragons
2,2,7t9g94,1.517018e+09,Escape From Flavortown,NaN,DungeonsAndDragons
3,3,1guf7p9,1.731963e+09,"My patient said to me, “You must be into sport...",NaN,DungeonsAndDragons
4,4,7nvhag,1.514995e+09,Persuasive Bard gets persuasive...,NaN,DungeonsAndDragons

,Unnamed: 0,id,created_utc,title,self_text,subreddit
0,0,7enkie,1.511319e+09,Love having everything you need for Pathfinder...,NaN,Pathfinder_RPG
1,1,10adsp3,1.673565e+09,Paizo Announces System-Neutral Open RPG License,NaN,Pathfinder_RPG
2,2,11b1br0,1.677271e+09,Thanks for playing Pathfinder.,We appreciate you.,Pathfinder_RPG
3,3,10dtypy,1.673907e+09,Newcomers; Archives of Nethys is free. It's no...,"Seriously, I've seen so many people lately com...",Pathfinder_RPG
4,4,10mlx2w,1.674829e+09,Pathfinder sales are through the roof followin...,NaN,Pathfinder_RPG

### Check the baseline

In [27]:
dnd.shape, pathfinder.shape

((1973, 6), (1992, 6))

In [29]:
dnd['self_text'].isnull().sum(), pathfinder['self_text'].isnull().sum()

(1324, 358)

### Set up a pipeline to transform the data

### Model Selection Criteria & Explanation

### Fit and Test the Model

### Model Analysis

### Tweak and Repeat